val debut2 = System.currentTimeMillis();
val data =sc.textFile("Z:/Doc/Cours/progDev/Perrin/data.csv")
val mappedData =data.map(line => line.split(","))
val selectedData =mappedData.map(line=> line(2))
val pmData =selectedData.filter(line => line.contains("PM"))
val amData =selectedData.filter(line => line.contains("AM"))
val pmData2 =pmData.map(line => line.split(" "))
val amData2= amData.map(line => line.split(" "))
val pmData3= pmData2.map(line => line(1).split(":"))
val amData3= amData2.map(line => line(1).split(":"))
val pmData4 =pmData3.map(line => line(0).toInt+12)
val amData4 =amData3.map(line => line(0).toInt)
val selectedData3 =amData4.union(pmData4)
val data0_4 =selectedData3.filter(line => (line < 5)).map(line =>("0_4",1)).reduceByKey(_+_)
val data4_8=selectedData3.filter(line => (line < 9 & line>4)).map(line=>("4_8",1)).reduceByKey(_+_)
val data8_12=selectedData3.filter(line => (line < 13 & line>8)).map(line=>("8_12",1)).reduceByKey(_+_)
val data12_16=selectedData3.filter(line => (line < 17 & line>12)).map(line=>("12_16",1)).reduceByKey(_+_)
val data16_20=selectedData3.filter(line => (line < 21 & line>16)).map(line=>("16_20",1)).reduceByKey(_+_)
val data20_24=selectedData3.filter(line => (line < 25 & line>20)).map(line=>("20_24",1)).reduceByKey(_+_)
val data_all=data0_4.union(data4_8).union(data8_12).union(data12_16).union(data16_20).union(data20_24)
data_all.saveAsTextFile("./out_question2")
print("Q2: ")
print(System.currentTimeMillis - debut2)
print(" ms")